remote_theme: coursweb/jk-theme
title: EEDEV 4 - ID311
description: Développement d'interfaces 4 - CMS
lang: fr-FR
# markdown: GFM
robots: noindex, nofollow
# menu 
chapters:
 - title: Cours Dev 4
   url: https://code.eracom-pedagogique.ch/eedev2-id311/
 - title: Référence CSS
   url: https://cours-web.ch/css/
 - title: Infos IMD
   url: https://eracom.ch/informations-eleves-id/
# - title: Plan de formation
#   url: https://code.eracom-pedagogique.ch/formation-imd-2020/   
# - title: Fontes IMD
#   url: https://code.eracom-pedagogique.ch/fontes-imd/  
 - title: Figma
   url: https://www.figma.com/files/team/1010489491753002544
# - title: 🧠 Podsie
#   url: https://student.podsie.org/
# pied de page   
footer_col_1: <ul class="contact-list">
  <li>Eracom, Lausanne</li>
  <li>2022</li></ul>
footer_col_2: <ul class="social-media-list"><li><a href="https://github.com/eracom-ID311/eedev4">Lien Github</a></li><li><a href="https://teams.microsoft.com/l/channel/19%3a42c0420f712e4886b486efd51534354c%40thread.tacv2/Dev%2520Interfaces%25204%2520(CMS)?groupId=8d768f21-970b-43c5-befc-7d4d6f71f426&tenantId=906ab908-04f9-4a80-ba9c-875a36e77bc1">Lien Teams</a></li></ul>
